//! End-to-end `scan` over a synthetic repo: grouping, language partitioning,
//! generated-file exclusion, floor behavior, ranking, JSON shape.

use reprise::config::Config;
use std::fs;
use tempfile::TempDir;

const RUST_FN_A: &str = r#"
pub fn summarize_scores(entries: &[(String, i64)], threshold: i64) -> Vec<String> {
    let mut summaries = Vec::new();
    let mut running_total = 0;
    for (label, score) in entries {
        if *score < threshold {
            continue;
        }
        running_total += score;
        let grade = if *score >= 90 { "excellent" } else { "poor" };
        summaries.push(format!("{label}: {score} ({grade})"));
    }
    if running_total > 250 {
        summaries.push(String::from("aggregate: high"));
    }
    summaries
}
"#;

// Type-2 variant of RUST_FN_A (renamed identifiers, changed literals)
const RUST_FN_B: &str = r#"
pub fn collect_report(items: &[(String, i64)], cutoff: i64) -> Vec<String> {
    let mut lines = Vec::new();
    let mut acc = 0;
    for (tag, points) in items {
        if *points < cutoff {
            continue;
        }
        acc += points;
        let band = if *points >= 85 { "stellar" } else { "weak" };
        lines.push(format!("{tag}: {points} ({band})"));
    }
    if acc > 400 {
        lines.push(String::from("aggregate: high"));
    }
    lines
}
"#;

const RUST_UNRELATED: &str = r#"
pub fn checksum(data: &[u8], salt: u8) -> u8 {
    let mut state = salt;
    for chunk in data.chunks(4) {
        for byte in chunk {
            state = state.wrapping_mul(31).wrapping_add(*byte);
        }
        state ^= 0x5A;
    }
    if state == 0 {
        state = salt.wrapping_add(7);
    }
    state
}
"#;

const PY_FN_A: &str = "def summarize_scores(entries, threshold):\n    summaries = []\n    running_total = 0\n    for label, score in entries:\n        if score < threshold:\n            continue\n        running_total += score\n        if score >= 90:\n            grade = \"excellent\"\n        else:\n            grade = \"poor\"\n        summaries.append(label + \": \" + str(score) + \" (\" + grade + \")\")\n    if running_total > 250:\n        summaries.append(\"aggregate: high\")\n    return summaries\n";

const PY_FN_B: &str = "def build_report(rows, cutoff):\n    lines = []\n    acc = 0\n    for tag, points in rows:\n        if points < cutoff:\n            continue\n        acc += points\n        if points >= 85:\n            band = \"stellar\"\n        else:\n            band = \"weak\"\n        lines.append(tag + \": \" + str(points) + \" (\" + band + \")\")\n    if acc > 400:\n        lines.append(\"aggregate: high\")\n    return lines\n";

fn build_repo() -> TempDir {
    let dir = TempDir::new().unwrap();
    let root = dir.path();
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(root.join("other")).unwrap();
    fs::write(
        root.join("src/a.rs"),
        format!("{RUST_FN_A}\n{RUST_UNRELATED}"),
    )
    .unwrap();
    fs::write(root.join("other/b.rs"), RUST_FN_B).unwrap();
    fs::write(root.join("src/mod_a.py"), PY_FN_A).unwrap();
    fs::write(root.join("other/mod_b.py"), PY_FN_B).unwrap();
    // A third copy inside a generated file: must be excluded (spec §5.1).
    fs::write(
        root.join("src/gen.rs"),
        format!("// @generated by proto-gen\n{RUST_FN_A}"),
    )
    .unwrap();
    dir
}

#[test]
fn scan_finds_language_partitioned_groups() {
    let repo = build_repo();
    let report = reprise::scan(repo.path(), &Config::default()).unwrap();

    assert_eq!(
        report.groups.len(),
        2,
        "expected exactly one rust + one python group, got: {:#?}",
        report.groups
    );
    for group in &report.groups {
        assert_eq!(
            group.members.len(),
            2,
            "group should have exactly 2 members"
        );
        assert_eq!(format!("{}", group.tier), "exact-normalized");
        // Language partitioning: members never mix languages.
        let exts: Vec<_> = group
            .members
            .iter()
            .map(|m| m.file.extension().unwrap().to_str().unwrap().to_string())
            .collect();
        assert!(
            exts.iter().all(|e| e == &exts[0]),
            "mixed-language group: {exts:?}"
        );
        // The generated file never appears.
        assert!(
            group.members.iter().all(|m| !m.file.ends_with("gen.rs")),
            "generated file leaked into findings"
        );
    }
}

#[test]
fn scan_reports_cross_directory_boost_and_line_spans() {
    let repo = build_repo();
    let report = reprise::scan(repo.path(), &Config::default()).unwrap();
    for group in &report.groups {
        assert!(group.value > 0.0);
        for m in &group.members {
            assert!(m.line_span.0 >= 1 && m.line_span.1 >= m.line_span.0);
            assert!(!m.name.is_empty());
        }
    }
}

#[test]
fn scan_json_is_serializable_and_complete() {
    let repo = build_repo();
    let report = reprise::scan(repo.path(), &Config::default()).unwrap();
    let json = serde_json::to_value(&report).unwrap();
    assert!(json["stats"]["units_indexed"].as_u64().unwrap() >= 5);
    assert_eq!(json["groups"].as_array().unwrap().len(), 2);
    let g = &json["groups"][0];
    assert!(g["tier"].is_string());
    assert!(g["members"].as_array().unwrap().len() == 2);
    assert!(g["members"][0]["file"].is_string());
    assert!(g["members"][0]["line_span"].is_array());
}

#[test]
fn floor_excludes_tiny_units() {
    let dir = TempDir::new().unwrap();
    // Two identical trivial getters: converge structurally, but sit below the
    // 40-token floor — the spec's "true-but-useless" class (§5.1). No findings.
    fs::write(
        dir.path().join("tiny.py"),
        "def get_a(self):\n    return self.a\n\ndef get_b(self):\n    return self.b\n",
    )
    .unwrap();
    let report = reprise::scan(dir.path(), &Config::default()).unwrap();
    assert!(report.groups.is_empty(), "sub-floor units must not report");
    assert!(report.stats.units_below_floor >= 2);
}

#[test]
fn parse_degraded_units_are_still_indexed() {
    // Spec §5.1: broken code is a primary use case — never silently dropped.
    let dir = TempDir::new().unwrap();
    let broken = "def summarize_scores(entries, threshold):\n    summaries = []\n    running_total = 0\n    for label, score in entries:\n        if score < threshold\n            continue\n        running_total += score\n        summaries.append(str(score))\n    return summaries\n";
    fs::write(dir.path().join("broken.py"), broken).unwrap();
    let report = reprise::scan(dir.path(), &Config::default()).unwrap();
    assert!(report.stats.units_indexed >= 1, "degraded unit was dropped");
    assert!(report.stats.parse_degraded_units >= 1);
}
